<?php if (!empty($this->novo_periodo)): ?>
    <div class="container-aviso aviso-periodo"><div class="ui-widget">
            <div style="padding: 0 .7em; width:90%; margin: 0 auto; margin-bottom: 2em" class="ui-state-error ui-corner-all">
                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                    Um novo período ainda não foi definido. Utilize os campos abaixo para fazer isso.
            </div>
        </div>
    </div>

<?php else: ?>
    <div class="container-aviso aviso-periodo"><div class="ui-widget">
            <div style="padding: 0 .7em; width:90%; margin: 0 auto; margin-bottom: 2em" class="ui-state-error ui-corner-all">
                <p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-alert"></span>
                    <b>Atenção!</b> As datas do calendário que ficarem fora do novo período serão excluídas. Isso inclui todos os lançamentos realizados para a data.
            </div>
        </div>
    </div>
<?php endif; ?>

<?= $this->form ?>

<script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/controle_periodo.js' ?>"></script>

<script>
    $(function() {
        form.iniForm();
        controle_periodo.ini('<?php echo $this->baseUrl() . "/imagens/calendar.png" ?>');
    });
</script>
