<?php if ($this->turma instanceof Application_Model_Turma): ?>
    <div class="container-aviso">
        <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
            <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
                <strong>Atenção:</strong> Ao cancelar a turma, não será mais possível incluir alunos nela  
            </p>   
        </div>
    </div>

    <h2>Informações da Turma</h2>

    <table class="form-dados" style="width: 60%;">
        <tr>
            <th width="5%">Nome: </th><td><?= $this->turma->getNomeTurma() ?></td>
        </tr>
    </table>

    <?= $this->form ?>

<?php else: ?>
    <p>Turma não encontrada.</p>

<?php endif; ?>