<?= $this->form ?>

<?php
if (!empty($this->professores))
    echo $this->table($this->professores, 3, true);
?>

<script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>

<script src="<?php echo $this->baseUrl() . '/js/functions.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/controle_turmas.js' ?>"></script>

<script>
    $(function() {
        $('#enviar').click(function(){
            return confirm('Deseja realmente excluir essa turma?');
        });
        
        controle_turmas.ini(
                '<?php echo $this->baseUrl() . "/imagens/calendar.png" ?>',
                '<?php echo $this->url(array('controller' => 'error', 'action' => 'error'), null, true); ?>',
                '<?php echo $this->url(array('controller' => 'error', 'action' => 'error'), null, true); ?>',
                3,
                '<?php echo $this->data(0) ?>',
                '<?php echo $this->data(1) ?>'
                );
        
        form.iniForm();
    });
</script>
