<?php
if ($this->turma instanceof Application_Model_Turma):
    $array_aprovacao = array(
        Application_Model_Aluno::$aluno_aprovado => 'Aprovado',
        Application_Model_Aluno::$aluno_reprovado => 'Reprovado',
        Application_Model_Aluno::$aluno_sem_status_aprovacao => '-');
    ?>
    <h2>Informações Gerais da Turma</h2>

    <table class="form-dados visualizacao" style="width: 60%;">
        <tr>
            <th style="width: 5%">Nome: </th><td colspan="2"><?php echo $this->turma->toString() ?></td>
        </tr>

        <tr>
            <th>Data Inicial: </th><td><?php echo $this->turma->getDataInicio(true) ?></td>
        </tr>

        <tr>
            <th>Data Término: </th><td><?php echo $this->turma->getDataFim(true) ?></td>
        </tr>

        <tr>
            <th>Horário: </th><td><?php echo $this->turma->horarioTurmaToString() ?></td>
        </tr>

        <tr>
            <?php
            $professores = $this->turma->getProfessores();
            ?>
            <th>Professores: </th><td>
                <?php if (!empty($professores)): ?>
                    <?php foreach ($professores as $professor): ?>
                        <?php echo $professor->getNomeVoluntario() . '<br/>' ?> 
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
        </tr>

    </table>

    <h2>Alunos da Turma</h2>

    <?php if (!empty($this->alunos)): ?>
        <table class="form_incrementa visualizacao" style="width: 80%;">
            <tr>
                <th style="">Nome</th>
                <th style="">Email</th>
                <th style="">CPF</th>
                <th style="">Pagamento</th>
                <th style="">Notas</th>
                <th style="">(%)Frequência</th>
                <th style="">Situação Final</th>
            </tr>

            <?php foreach ($this->alunos as $aluno): ?>
                <?php if ($aluno instanceof Application_Model_Aluno): ?>
                    <?php $turmas = $aluno->getCompleteTurmas(); ?>
                    <tr>
                        <td><?php echo $aluno->getNomeAluno() ?></td>
                        <td><?php echo $aluno->getEmail() ?></td>
                        <td><?php echo $aluno->getCpf() ?></td>
                        <td><?php echo ($turmas[$this->id_turma][Application_Model_Aluno::$index_pagamento_turma] instanceof Application_Model_Pagamento) ? $turmas[$this->id_turma][Application_Model_Aluno::$index_pagamento_turma]->getSituacao() : '' ?></td>
                        <td>
                            <?php foreach ($turmas[$this->id_turma][Application_Model_Aluno::$index_notas_turma] as $nota): ?>
                                <?php if ($nota instanceof Application_Model_Nota): ?>
                                    <?php echo $nota->toString() ?><br>
                                <?php endif ?>
                            <?php endforeach; ?>
                            <?php echo $aluno->getNotaAcumulada($this->id_turma) ?>
                        </td>
                        <td><?php echo $aluno->getPorcentagemFaltas($turmas[$this->id_turma][Application_Model_Aluno::$index_turma]->getIdTurma(), $this->total_aulas, true) ?></td>
                        <td><?php echo $array_aprovacao[$turmas[$this->id_turma][Application_Model_Aluno::$index_aprovacao_turma]]?></td>
                    </tr>
                <?php endif ?>
            <?php endforeach; ?>

        </table>

    <?php else: ?>
        <p>Não há nenhum aluno cadastro na turma escolhida.</p>

    <?php endif; ?>

    <table class="form-dados visualizacao" style="width: 60%;">
        <tr>
            <td><a href="<?php echo $this->url(array('controller' => 'turma', 'action' => 'index'), null, true) ?>">Voltar</a></td>
        </tr>           
    </table>

<?php else: ?>
    <p>Turma não encontrada.</p>

<?php endif; ?>