<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Informações da Turma</h2>

    <?= $this->element->id_turma ?>

    <table class="form-dados">
        <tr>
            <td><?= $this->element->nome_turma ?></td>
            <td></td>
        </tr>

        <tr>
            <td><?= $this->element->curso ?></td>
        </tr>

        <tr>
            <td><?= $this->element->disciplina ?></td>
        </tr>
        
        <tr>
            <td><?= $this->element->sala ?></td>
            <td></td>
        </tr>
    </table>

    <h2>Professores</h2>
    <table class="form-dados">
        <tr>
            <td><?= $this->element->professor ?></td>
            <td><?= $this->element->incluir_professor ?></td>
        </tr>
    </table>

    <table class="form_incrementa" cellpadding="0" cellspacing="0"></table>

    <h2>Datas e Horários</h2>
    <table class="form-dados">
        <tr>
            <td><?= $this->element->data_inicio ?></td>
            <td><?= $this->element->data_fim ?></td>
        </tr>

        <tr>
            <td><?= $this->element->horario_inicio ?></td>
            <td><?= $this->element->horario_fim ?></td>
        </tr>

    </table>

    <table class="submit" style="float: left;">
        <tr>
            <td><?= $this->element->enviar ?></td>
            <td><?= $this->element->cancelar ?></td>
        </tr>
    </table>

</form>