<?php
$url = new Zend_View_Helper_Url();
?>

<div id="mensagem-ajax">Por favor, aguarde um momento.</div>

<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Dados do Aluno</h2>
    <div class="obs">
        <p>Caso encontre o aluno desejado ao digitar um nome clique nele para alterá-lo.</p>
    </div>

    <table class="form-dados" style="width: 85%;">
        <tr>
            <td colspan="3">
                <?= $this->element->nome_aluno ?>
            </td>
        </tr>
        <tr>
            <td><?= $this->element->rg ?></td>
            <td><?= $this->element->data_registro ?></td>
            <td><?= $this->element->cpf ?></td>
        </tr>

        <tr>
            <td><div class="checkbox"><?= $this->element->is_cpf_responsavel ?></div></td>
            <td colspan="2"><div class="escondido nome-responsavel"><?= $this->element->nome_responsavel ?></div></td>
        </tr>

        <tr>
            <td><?= $this->element->telefone ?></td>
            <td><?= $this->element->celular ?></td>
            <td><?= $this->element->sexo ?></td>
        </tr>

        <tr>
            <td><?= $this->element->data_nascimento ?></td>
            <td colspan="2"><?= $this->element->email ?></td>
        </tr>

        <tr>
            <td colspan="3">
                <div class="obs">
                    <p>Ao preencher o campo "cep" o endereço é buscado automaticamente.</p>
                </div>
            </td>
        </tr>
        <tr>
            <td><?= $this->element->cep ?><div id="loading" class="loading"></div></td>
            <td><?= $this->element->estado ?></td>
            <td><?= $this->element->cidade ?></td>
        </tr>

        <tr>
            <td colspan="3"><?= $this->element->endereco ?></td>
        </tr>

        <tr>
            <td><?= $this->element->numero ?></td>
            <td><?= $this->element->complemento ?></td>
            <td><?= $this->element->bairro ?></td>
        </tr>

        <tr>
            <td colspan="2"><?= $this->element->escolaridade ?></td>
            <td></td>
        </tr>
    </table>

    <h2>Turmas Matriculadas</h2>

    <div class="obs">
        <p>Só é permitida a alteração das turmas do período atual.</p>
    </div>

    <table class="form-dados" id="busca_turmas">
        <tr colspan="2" class="quantidade_turmas">
            <td><?= $this->element->quantidade_turmas ?></td>
        </tr>
        <tr>
            <td colspan="2"><?= $this->element->curso ?></td>
        </tr>
        <tr>
            <td colspan="2"><?= $this->element->disciplina ?></td>
        </tr>
        <tr>
            <td><?= $this->element->turma ?></td>
            <td class="incluir_turma"><?= $this->element->incluir_turma ?></td>
            <td id="quant_alunos_cadastrados"></td>
        </tr>
    </table>

    <table class="form_incrementa" id="turmas_aluno" cellpadding="0" cellspacing="0"></table>

    <div id="container_turmas_escolhidas">
        <h2>Gerenciamento das Turmas Escolhidas</h2>

        <table class="form-dados">
            <tr>
                <td><?= $this->element->pagamento_turma ?></td>
            </tr>

            <tr id="container_condicao_matricula">
                <td><?= $this->element->condicao_matricula ?></td>
            </tr>

            <tr id='container_tipo_isencao_pendencia'>
                <td><?= $this->element->tipo_isencao_pendencia ?></td>
            </tr>
        </table>
    </div>

    <div id="container_alimentos">
        <h3>Alimentos</h3>

        <table id="table_gerenciamento_alimentos" class="form-dados">    
            <tr>
                <td><?= $this->element->alimento ?></td>
                <td style="vertical-align: middle">
                    <a target="_blank" href="<?php echo $url->url(array('controller' => 'alimento', 'action' => 'cadastrar')) ?>" id="add-alimento">Adicionar Tipo de Alimento</a>
                    <div id="atualizar_alimentos">Atualizar</div>
                    <div id="loading-alimentos" class="loading"></div>
                </td>
            </tr>

            <tr>
                <td><?= $this->element->quantidade_alimento ?></td>
                <td><?= $this->element->incluir_alimento ?></td>
            </tr> 
        </table>

        <div id="container_alimentos_turmas"></div>
    </div>
    
    <div id="container_pagamentos">
        <h3>Pagamento</h3>

        <table class="form-dados">
            <tr id='container_recibo'>
                <td><?= $this->element->num_recibo ?></td>
            </tr>

            <tr>
                <td id="container_valor_pago"><?= $this->element->valor_pago ?></td>
                <td id="container_btn_registro_pagamento"><?= $this->element->registrar_pagamento ?></td>
            </tr>    
        </table>
    </div>

    <div id="container_pagamentos_registrados">
        <h2>Pagamentos Registrados</h2>

        <table id="table_pagamentos_turmas" class="escondido form_incrementa" cellpadding="0" cellspacing="0"></table>
    </div>
    
    <table class="submit">
        <tr>
            <td><?= $this->element->enviar ?></td>
            <td><?= $this->element->cancelar ?></td>
        </tr>
    </table>


    <?= $this->element->cidade_escolhida ?>
    <?= $this->element->estado_escolhido ?>
    <?= $this->element->id_aluno ?>


</form>