<form enctype="application/x-www-form-urlencoded" action="" method="post">

  <h2>Sistema de cadastro</h2>

  <table class="form-dados" style="float: left;">
      <tr>
          <td>
              <?= $this->element->texto_inicial ?>
          </td>
      </tr>
      <tr>
          <td>
            <div class="radio">
                <span class="span-radio">Liberação do cadastro</span>
                <?= $this->element->somente_veterano ?>
            </div>
          </td>
      </tr>
  </table>

  <table class="submit" style="float: left;">
      <tr>
          <td><?= $this->element->enviar ?></td>
          <td><?= $this->element->cancelar ?></td>
      </tr>
  </table>


</form>
