<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <table class="form-dados consulta">
        <tr>
            <td style="width:40%"><?= $this->element->nome_turma ?></td>
            <td style="width:20%"><?= $this->element->disciplina ?></td>
            <td style="width:20%"><?= $this->element->periodo ?></td>
            <td style="width:20%"><?= $this->element->buscar ?></td>
        </tr>
    </table>

</form>