<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Lançamento de Notas</h2>

    <?= $this->element->data ?>

    <div class="obs">Escolha uma turma, aguarde o carregamento dos alunos, selecione uma atividade e faça o lançamento. </div>

    <div class="container">
        <table class="form-dados" style="width: 40%;">
            <tr>
                <td><?= $this->element->curso ?></td>
            </tr>

            <tr>
                <td><?= $this->element->disciplina ?></td>
            </tr>

            <tr>
                <td><?= $this->element->turma ?></td>
            </tr>
        </table>

        <div id="container_atividade">
            <h2>Atividade</h2>

            <table class="form-dados" style="width: 40%;">
                <tr>
                    <td><?= $this->element->atividade ?></td>
                </tr>

            </table>
        </div>
    </div>

    <div id="notas_alunos" class="nota-container"></div>

    <table class="submit">
        <tr>
            <td style="width: 33%"><?= $this->element->enviar ?></td>
            <td><?= $this->element->cancelar ?></td>
        </tr>
    </table>
</form>