<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <table class="form-dados">
        <tr>
            <td colspan="3"><?= $this->element->nome_aluno ?></td>
        </tr>
        <tr>
            <td><?= $this->element->rg ?></td>
            <td><?= $this->element->cpf ?></td>
            <td><div class="checkbox"><?= $this->element->is_responsavel ?></div></td>
        </tr>
        
        <tr>
            <td><?= $this->element->buscar ?></td>
        </tr>
    </table>
    
</form>
