<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Período de Atividades</h2>

    <?= $this->element->id_periodo ?>
    <table class="form-dados" style="width: 50%">
        <tr>
            <td><?= $this->element->nome_periodo ?></td>
        </tr>

        <tr>
            <td><?= $this->element->data_inicio ?></td>
        </tr>

        <tr>
            <td><?= $this->element->data_termino ?></td>
        </tr>
    </table>

    <h2>Pagamentos</h2>
    <table class="form-dados" style="width: 50%">
        <tr>
            <td><?= $this->element->valor_liberacao_periodo ?></td>
        </tr>

        <tr>
            <td><?= $this->element->quantidade_alimentos ?></td>
        </tr>
    </table>

    <h2>Aprovação</h2>
    <table class="form-dados" style="width: 50%">
        <tr>
            <td><?= $this->element->freq_min_aprov ?></td>
        </tr>

        <tr>
            <td><?= $this->element->total_pts_periodo ?></td>
        </tr>

        <tr>
            <td><?= $this->element->min_pts_aprov ?></td>
        </tr>
    </table>


    <table class="submit" style="float: left;">
        <tr>
            <td><?= $this->element->enviar ?></td>
            <td><?= $this->element->cancelar ?></td>
        </tr>
    </table>

</form>