<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Calendário Letivo do Projeto</h2>

    <table class="form-dados" style="width: 40%;">
        <tr>
            <td colspan="3"><?= $this->element->data ?></td>
        </tr>

    </table>

    <div class="checkbox">
        <?= $this->element->todos_sabados ?>
    </div>
    
    <h2>Datas Selecionadas</h2>

    <div id='datas-escolhidas'></div>

    <table class="submit">
        <tr>
            <td><?= $this->element->enviar ?></td>
            <td><?= $this->element->cancelar ?></td>
        </tr>
    </table>

</form>