<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Informações da Disciplina</h2>
    <?= $this->element->id_disciplina ?>
    <table class="form-dados">
        <tr>
            <td colspan="3"><?= $this->element->nome_disciplina ?></td>
        </tr>
        <tr>
            <td colspan="1"><?= $this->element->vagas_do_curso ?></td>
            <td colspan="1"><?= $this->element->fila_de_nivelamento ?></td>
            <td colspan="1"><?= $this->element->fila_de_espera ?></td>
        </tr>
        <tr>
            <td colspan="1"><?= $this->element->total_vagas_do_curso ?></td>
            <td colspan="1"><?= $this->element->total_fila_de_nivelamento ?></td>
            <td colspan="1"><?= $this->element->total_fila_de_espera ?></td>
        </tr>
        <tr>
            <td colspan="1"><?= $this->element->idade_minima ?></td>
        </tr>

        <tr>
            <td><?= $this->element->id_curso ?></td>
        </tr>

        <tr>
            <td><?= $this->element->pre_requisito ?></td>
            <td><?= $this->element->incluir_pre_requisito ?></td>
        </tr>
    </table>

    <table class="form_incrementa" cellpadding="0" cellspacing="0"></table>

    <table class="form-dados">
        <tr>
            <td><?= $this->element->ementa_disciplina ?></td>
        </tr>
    </table>

    <table class="submit" style="float: left;">
        <tr>
            <td><?= $this->element->enviar ?></td>
            <td><?= $this->element->cancelar ?></td>
        </tr>
    </table>

</form>
