<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <h2>Dados de Acesso ao Sistema</h2>
    <table class="form-dados" style="width: 30%">
        <tr>
            <td><?= $this->element->login ?></td>
        </tr>

        <tr>
            <td><?= $this->element->pass ?></td>
        </tr>
    </table>
    <table class="submit" style="float: left; width:25%">
        <tr>
            <td><?= $this->element->enviar ?></td>
        </tr>
    </table>

</form>