<h2>Consultar Pre-Matrícula</h2>

<?= $this->form ?>

<?php if ($this->resultado_busca instanceof Zend_Paginator) : ?>
    <?php if (count($this->resultado_busca) > 0) : ?>
        <div id='resultado-busca'>
            <h3>Resultados da Busca</h3>
            <span>Foram encontrados (<?= $this->resultado_busca->getTotalItemCount() ?>) registros</span>
            <table>
                <tr>
                    <th>Numero Comprovante</th>
                    <th>ID Aluno</th>
                    <th>CPF Aluno</th>
                    <th>Nome Aluno</th>
                    <th>Disciplina</th>
                    <th>Turma</th>
                    <th>Veterano</th>
                    <th>Vaga Garantida</th>
                    <th>Fila de Nivelamento</th>
                    <th>Fila de Espera</th>
                </tr>

                <?php foreach ($this->resultado_busca as $pre_matricula) : ?>
                    <tr>
                        <td><?= $pre_matricula->getNumeroComprovante() ?></td>
                        <td><?= $pre_matricula->getIdAluno() ?></td>
                        <td><?= $pre_matricula->getCPFAluno() ?></td>
                        <td><?= $pre_matricula->getNomeAluno() ?></td>
                        <td><?= $pre_matricula->getNomeDisciplina() ?></td>
                        <td><?= $pre_matricula->getTurma() ?></td>
                        <td><?= $pre_matricula->getVeterano() != 0 ? 'X' : '' ?></td>
                        <td><?= $pre_matricula->getVagaGarantida() != 0 ? 'X' : '' ?></td>
                        <td><?= $pre_matricula->getFilaDeNivelamento() != 0 ? 'X' : '' ?></td>
                        <td><?= $pre_matricula->getFilaDeEspera() != 0 ? 'X' : '' ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <?php echo $this->paginationControl($this->resultado_busca, 'Sliding', 'Decorators/pagination.phtml'); ?>

    <?php else : ?>
        <script>exibeMensagem('Nenhum pre-matrícula foi encontrada.', 'Busca de Pre-Matrícula');</script>

    <?php endif; ?>
<?php endif; ?>
