<h2>Consultar Aluno</h2>

<div id="link-cadastrar">
    <a href = "<?php echo $this->url(array('controller' => 'aluno', 'action' => 'cadastrar'), null, true) ?>">Cadastrar Novo Aluno</a>     
</div>

<?= $this->form ?>

<?php if ($this->resultado_busca instanceof Zend_Paginator) : ?>
    <?php if (count($this->resultado_busca) > 0) : ?>
        <div id='resultado-busca'>
            <h3>Resultados da Busca</h3>
            <span>Foram encontrados (<?= $this->resultado_busca->getTotalItemCount() ?>) registros</span>
            <table>
                <tr>
                    <th>Nome do Aluno</th>
                    <th>CPF</th>
                    <th colspan=3>Opções</th>
                </tr>

                <?php foreach ($this->resultado_busca as $aluno) : ?>
                    <tr>
                        <td><?= $aluno->getNomeAluno() ?></td>
                        <td><?= $aluno->getCpf() ?></td>
                        <?php if (!$this->is_fim_periodo_atual): ?>
                            <td><a href='<?= $this->url(array('controller' => 'aluno', 'action' => 'alterar', 'aluno' => $aluno->getIdAluno(true)), null, true) ?>'>Alterar</a></td>
                            <?php if ($aluno->isAtivo()): ?>
                                <td><a href='<?= $this->url(array('controller' => 'aluno', 'action' => 'desligar-aluno', 'aluno' => $aluno->getIdAluno(true)), null, true) ?>'>Desligar Aluno</a></td>
                            <?php else: ?>
                                <td><a href='<?= $this->url(array('controller' => 'aluno', 'action' => 'ativar-aluno', 'aluno' => $aluno->getIdAluno(true)), null, true) ?>'>Ativar Aluno</a></td>
                            <?php endif; ?>
                        <?php endif; ?>
                        <td><a href='<?= $this->url(array('controller' => 'aluno', 'action' => 'visualizar', 'aluno' => $aluno->getIdAluno(true)), null, true) ?>'>Visualizar</a></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <?php echo $this->paginationControl($this->resultado_busca, 'Sliding', 'Decorators/pagination.phtml'); ?>

    <?php else : ?>
        <script>exibeMensagem('Nenhum aluno foi encontrado.', 'Busca de Aluno');</script>

    <?php endif; ?>
<?php endif; ?>

<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/additional-methods.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>
<script>
    $(function() {
        form.iniForm();
    });
</script>
