<?php echo $this->form ?>

<script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>

<script src="<?php echo $this->baseUrl() . '/js/functions.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/controle_atividades.js' ?>"></script>

<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>

<script>
    $(function() {
        var datas_atividades = $.parseJSON('<?php echo $this->datas_atividade; ?>');

        form.iniForm();
        
        controle_atividades.ini(
                '<?php echo $this->url(array('controller' => 'disciplina', 'action' => 'buscar-disciplinas'), null, true); ?>',
                '<?php echo $this->url(array('controller' => 'turma', 'action' => 'buscar-turmas'), null, true); ?>',
                '<?php echo $this->url(array('controller' => 'atividade', 'action' => 'busca-atividades-turma'), null, true); ?>',
                '<?php echo $this->baseUrl() . "/imagens/calendar.png" ?>',
                '<?php echo $this->data(0) ?>',
                '<?php echo $this->data(1) ?>',
                datas_atividades,
                '<?php echo $this->data(2) ?>',
                1
        );
    });
</script>