<?php if (empty($this->not_found)): ?>
    <?php echo $this->form ?>

    <script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>

    <script src="<?php echo $this->baseUrl() . '/js/functions.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/controle_atividades.js' ?>"></script>

    <script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>

    <script>
        $(function() {
            var datas_atividades = $.parseJSON('<?php echo $this->datas_atividade; ?>');
            form.iniForm();

            controle_atividades.ini(
                    '<?php echo $this->url(array('controller' => 'error', 'action' => 'error'), null, true); ?>',
                    '<?php echo $this->url(array('controller' => 'error', 'action' => 'error'), null, true); ?>',
                    '<?php echo $this->url(array('controller' => 'error', 'action' => 'error'), null, true); ?>',
                    '<?php echo $this->baseUrl() . "/imagens/calendar.png" ?>',
                    '<?php echo $this->data(0) ?>',
                    '<?php echo $this->data(1) ?>',
                    datas_atividades,
                    '<?php echo $this->data(2) ?>',
                    3);
        });

    </script>


<?php else: ?>
    <div class="aviso">A atividade não foi encontrada, ou ela já foi excluída ou nunca foi criada.</div>
<?php endif; ?>