<?php if ($this->disciplina instanceof Application_Model_Disciplina): ?>
    <div class="container-aviso">
        <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
            <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
                <strong>Atenção: </strong> Mensagem
            </p>   
        </div>
    </div>

    <h2>Informações da Disciplina</h2>

    <table class="form-dados" style="width: 20%;">
        <tr>
            <th>Nome: </th><td><?= $this->disciplina->getNomeDisciplina() ?></td>
        </tr>
    </table>

    <?= $this->form ?>

<?php else: ?>
    <p>Disciplina não foi encontrada ou ela já foi ativada</p>

<?php endif; ?>