<?php if ($this->disciplina instanceof Application_Model_Disciplina): ?>
    <div class="container-aviso">
        <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
            <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
                <strong>Atenção:</strong> Ao cancelar a disciplina, todas as turmas dela serão canceladas  
            </p>   
        </div>
    </div>

    <h2>Informações da Disciplina</h2>

    <table class="form-dados" style="width: 60%;">
        <tr>
            <th width="5%">Nome: </th><td><?= $this->disciplina->getNomeDisciplina() ?></td>
        </tr>
    </table>

    <?= $this->form ?>

<?php else: ?>
    <p>Disciplina não encontrada.</p>

<?php endif; ?>