<h2>Consultar Disciplina</h2>

<div id="link-cadastrar">
    <a href = "<?php echo $this->url(array('controller' => 'disciplina', 'action' => 'cadastrar'), null, true) ?>">Cadastrar Disciplina</a>     
</div>

<?= $this->form ?>

<?php if ($this->resultado_busca instanceof Zend_Paginator) : ?>
    <?php if (count($this->resultado_busca) > 0) : ?>
        <div id='resultado-busca'>
            <h3>Resultados da Busca</h3>
            <span>Foram encontrados (<?= $this->resultado_busca->getTotalItemCount() ?>) registros</span>
            <table>
                <tr>
                    <th>Nome da Disciplina</th>
                    <th>Nome do Curso</th>
                    <th colspan="2">Opções</th>
                </tr>

                <?php foreach ($this->resultado_busca as $disciplina) : ?>
                    <tr>
                        <td><?= $disciplina->getNomeDisciplina() ?></td>
                        <td><?= $disciplina->getCurso()->getNomeCurso() ?></td>

                        <?php if ($disciplina->getStatus() == Application_Model_Disciplina::status_ativo): ?>
                            <td><a href='<?= $this->url(array('controller' => 'disciplina', 'action' => 'alterar', 'disciplina' => $disciplina->getIdDisciplina(true)), null, true) ?>'>Alterar</a></td>                     
                            <td><a href='<?= $this->url(array('controller' => 'disciplina', 'action' => 'cancelar', 'disciplina' => $disciplina->getIdDisciplina(true)), null, true) ?>'>Cancelar</a></td>                     

                        <?php else: ?>
                            <td colspan="2"><a href='<?= $this->url(array('controller' => 'disciplina', 'action' => 'ativar', 'disciplina' => $disciplina->getIdDisciplina(true)), null, true) ?>'>Ativar</a></td>
                        <?php endif; ?>
            <!--<td><a href='<?= $this->url(array('controller' => 'disciplina', 'action' => 'excluir', 'disciplina' => $disciplina->getIdDisciplina(true)), null, true) ?>'>Excluir</a></td>-->
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <?php echo $this->paginationControl($this->resultado_busca, 'Sliding', 'Decorators/pagination.phtml'); ?>

    <?php else : ?>
        <script>exibeMensagem('Nenhuma disciplina foi encontrada.', 'Busca de Disciplinas');</script>

    <?php endif; ?>
<?php endif; ?>