<?= $this->form ?>

<?php
if (!empty($this->disciplinas))
    echo $this->table($this->disciplinas, 2);
?>

<script type="text/javascript" src="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cidades-estados-js/cidades-estados-1.2-utf8.js"></script>
<script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>

<script src="<?php echo $this->baseUrl() . '/js/functions.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/controle_voluntarios.js' ?>"></script>

<script>
    $(function() {
        form.iniForm('<?= $this->url(array('controller' => 'ajax', 'action' => 'cep'), null, true) ?>');
        controle_voluntarios.ini(
                '<?php echo $this->url(array('controller' => 'voluntario', 'action' => 'verifica-voluntario'), null, true); ?>',
                '<?php echo $this->url(array('controller' => 'disciplina', 'action' => 'buscar-disciplinas'), null, true); ?>',
                '<?php echo $this->baseUrl() . "/imagens/calendar.png" ?>',
                '<?php echo base64_encode(Application_Model_Voluntario::$status_desligado) ?>',
                '<?php echo Application_Model_Voluntario::$atividade_aulas ?>',
                2
                );
    });
</script>