<?php if ($this->voluntario instanceof Application_Model_Voluntario): ?>
    <h2>Informações do Voluntário</h2>

    <table class="form-dados" style="width: 60%;margin-bottom: 3em;">
        <tr>
            <th width="10%">Nome: </th><td><?= $this->voluntario->getNomeVoluntario() ?></td>
        </tr>
        <tr>
            <th>CPF: </th><td><?= $this->voluntario->getCpf() ?></td>
        </tr>
    </table>

    <?= $this->form ?>

    <script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/ui.datepicker-pt-BR.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
    <script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>

    <script>
        $(function() {
            $('#data_desligamento').datepicker({
                buttonText: "Clique para selecionar uma data",
                showOn: "button",
                buttonImageOnly: true,
                buttonImage: '<?php echo $this->baseUrl() . "/imagens/calendar.png" ?>'
            });
            form.iniForm('');
        });
    </script>


<?php else: ?>
    <p>Voluntário não encontrado, ou ele já foi desligado do projeto</p>

<?php endif; ?>