<?php echo $this->form; ?>


<script src="<?php echo $this->baseUrl() . '/js/jquery.maskedinput.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/jquery.validate.min.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/form.js' ?>"></script>
<script src="<?php echo $this->baseUrl() . '/js/functions.js' ?>"></script>

<script src="<?php echo $this->baseUrl() . '/js/controle_distribuicao.js' ?>"></script>

<script>
    $(function() {
        form.iniForm('');
    });
</script>